micronaut:
  application:
    name: resilience4j-micronaut-demo
  server:
    port: 8086
  metrics:
    enabled: true
    sensitive: false
    export:
      prometheus:
        enabled: true

info.application.name: ${micronaut.application.name}

endpoints:
  info:
    enabled: true
    sensitive: false

resilience4j:
  retry:
    enabled: true
    configs:
      default:
        maxRetryAttempts: 3
        wait-duration: 5s
        retryExceptions:
          - io.micronaut.http.exceptions.HttpStatusException
          - java.util.concurrent.TimeoutException
          - java.io.IOException
        ignoreExceptions:
          - resilience4j.micronaut.demo.exception.BusinessException
    instances:
      backendA:
        baseConfig: default
      backendB:
        baseConfig: default
